tfvars_server_ami = "ami-002f6e91abff6eb96"
tfvars_server_instance_type = "t2.nano"
tfvars_server_1_instance_tag = "tfvars_server_1_dev"
tfvars_server_2_instance_tag = "tfvars_server_2_dev"
tfvars_bucket = "tfvars_bucket_s_dev"